### PR TITLE
Adding functions from PR#3232, #3389, #3480

### PR DESCRIPTION
**Pull request by deniszh**
Adding newest changes for graphite translator

### CODE REVIEW

**Review by bdunavant — APPROVED** [review]

**Review by bdunavant — CHANGES_REQUESTED** [review]
Actually, this before the updates to aggregatewithwildcards using graphite:removenode.  That will need to be updated before we merge this one.

**Comment by deniszh** [comment]
Is graphite:removenode already merged? Will make fixes then.

**Comment by deniszh** [comment]
@bdunavant : requested changes are made

**Review by bdunavant — APPROVED** [review]
LGTM - waiting until code is deployed to all clusters before merging

**Pull request merged**
